name: "Hello World"

on:
  push:
    branches:
    - master
    - production 
    
    
jobs:
 hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        uses: actions/checkout@v2

      - name: Run Hello World script
        run:           echo "Hello, World!"
          echo "This is a test workflow."